version: "3.7"
volumes:
  db_data:

networks:
  app-network:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app-network
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "topic1:1:1"


  kafka_configurer:
    build: kafka_configurer
    container_name: kafka_configurer
    restart: on-failure
    depends_on:
      - kafka
      - zookeeper
    networks:
      - app-network

  orchestrator:
    build: orchestrator
    container_name: orchestrator
    restart: on-failure
    depends_on:
      - kafka
      - zookeeper
    networks:
      - app-network

  eureka:
    build: eureka
    container_name: eureka
    restart: on-failure
    depends_on:
      - kafka
    networks:
      - app-network

  gateway:
    build: gateway
    container_name: gateway
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - eureka
    networks:
      - app-network
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

  maria_db:
    container_name: maria_db
    image: mariadb
    ports:
      - "3307:3306"
    networks:
      - app-network
    environment:
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    volumes:
      - ./init:/docker-entrypoint-initdb.d


  catalogue_service:
    build: catalogue_service
    container_name: catalogue_service
    restart: on-failure
    depends_on:
      - maria_db
      - eureka
      - gateway
    command: sh -c 'bin/wait-for maria_db:3306 -- bundle exec rails s'
    networks:
      - app-network
    environment:
      eureka.client.serviceUrl.defaultZone: "http://eureka:8761/eureka/"
      spring.datasource.driverClassName: "org.mariadb.jdbc.Driver"
      spring.datasource.url: "jdbc:mariadb://maria_db:3306/catalogue"
      spring.datasource.username: "root"
      spring.datasource.password: "admin"
      server.port: 8100
      server.address: 0.0.0.0

  wallet_service:
    build: wallet_service
    container_name: wallet_service
    restart: on-failure
    depends_on:
      - maria_db
      - eureka
      - gateway
    command: sh -c 'bin/wait-for maria_db:3306 -- bundle exec rails s'
    networks:
      - app-network
    environment:
      eureka.client.serviceUrl.defaultZone: "http://eureka:8761/eureka/"
      spring.datasource.driverClassName: "org.mariadb.jdbc.Driver"
      spring.datasource.url: "jdbc:mariadb://maria_db:3306/wallet"
      spring.datasource.username: "root"
      spring.datasource.password: "admin"
      server.port: 8200
      server.address: 0.0.0.0

  order_service:
    build: order_service
    container_name: order_service
    restart: on-failure
    depends_on:
      - maria_db
      - eureka
      - gateway
    command: sh -c 'bin/wait-for maria_db:3306 -- bundle exec rails s'
    networks:
      - app-network
    environment:
      eureka.client.serviceUrl.defaultZone: "http://eureka:8761/eureka/"
      spring.datasource.driverClassName: "org.mariadb.jdbc.Driver"
      spring.datasource.url: "jdbc:mariadb://maria_db:3306/order_db"
      spring.datasource.username: "root"
      spring.datasource.password: "admin"
      server.port: 8300
      server.address: 0.0.0.0

  warehouse_service:
    build: warehouse_service
    container_name: warehouse_service
    restart: on-failure
    depends_on:
      - maria_db
      - eureka
      - gateway
    command: sh -c 'bin/wait-for maria_db:3306 -- bundle exec rails s'
    networks:
      - app-network
    environment:
      eureka.client.serviceUrl.defaultZone: "http://eureka:8761/eureka/"
      spring.datasource.driverClassName: "org.mariadb.jdbc.Driver"
      spring.datasource.url: "jdbc:mariadb://maria_db:3306/warehouse"
      spring.datasource.username: "root"
      spring.datasource.password: "admin"
      server.port: 8400
      server.address: 0.0.0.0
