server:
  port: 8400
spring:
  application:
    name: warehouse
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
